Enhavo\Bundle\BlockBundle\Entity\Node:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: uuid
            groups: [default]

    properties:
        block:
            - Valid:
                  groups: [default]
        children:
            - Valid:
                  groups: [default]
        uuid:
            - Uuid:
                  groups: [default]

Enhavo\Bundle\BlockBundle\Model\Block\VideoBlock:
    properties:
        url:
            - Enhavo\Bundle\BlockBundle\Validator\Constraints\VideoUrl:
                  groups: [default]

Enhavo\Bundle\BlockBundle\Model\Column\OneColumnBlock:
    properties:
        column:
            - Valid:
                  groups: [default]

Enhavo\Bundle\BlockBundle\Model\Column\TwoColumnBlock:
    properties:
        columnOne:
            - Valid:
                  groups: [default]
        columnTwo:
            - Valid:
                  groups: [default]

Enhavo\Bundle\BlockBundle\Model\Column\ThreeColumnBlock:
    properties:
        columnOne:
            - Valid:
                  groups: [default]
        columnTwo:
            - Valid:
                  groups: [default]
        columnThree:
            - Valid:
                  groups: [default]
